### ISSUE TITLE
Exception from sub filteredUsers

### ISSUE THREAD

**Issue by leolara** [hharnisc/meteor-accounts-admin-ui-bootstrap-3#32]
When I install this package I get this error in the server console:

```
I20150604-14:23:57.191(2)? Exception from sub filteredUsers id ckXfEK2kAkhxtAZnc Error: Did not check() all arguments during publisher 'filteredUsers'
I20150604-14:23:57.191(2)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (/Users/leo/src/zirra-web/.meteor/local/build/programs/server/packages/check.js:375:13)
I20150604-14:23:57.191(2)?     at Object.Match._failIfArgumentsAreNotAllChecked (/Users/leo/src/zirra-web/.meteor/local/build/programs/server/packages/check.js:130:16)
I20150604-14:23:57.191(2)?     at maybeAuditArgumentChecks (/Users/leo/src/zirra-web/.meteor/local/build/programs/server/packages/ddp.js:2442:18)
I20150604-14:23:57.191(2)?     at [object Object]._.extend._runHandler (/Users/leo/src/zirra-web/.meteor/local/build/programs/server/packages/ddp.js:1778:17)
I20150604-14:23:57.191(2)?     at [object Object].MeteorX.Subscription._runHandler (/Users/leo/src/zirra-web/.meteor/local/build/programs/server/packages/meteorhacks_unblock.js:61:22)
I20150604-14:23:57.192(2)?     at [object Object].MeteorX.Session._startSubscription (/Users/leo/src/zirra-web/.meteor/local/build/programs/server/packages/meteorhacks_unblock.js:49:7)
I20150604-14:23:57.192(2)?     at [object Object]._.extend.protocol_handlers.sub (/Users/leo/src/zirra-web/.meteor/local/build/programs/server/packages/ddp.js:1410:12)
I20150604-14:23:57.192(2)?     at [object Object].MeteorX.Session.protocol_handlers.sub (/Users/leo/src/zirra-web/.meteor/local/build/programs/server/packages/meteorhacks_unblock.js:23:15)
I20150604-14:23:57.192(2)?     at /Users/leo/src/zirra-web/.meteor/local/build/programs/server/packages/ddp.js:1374:43
```

**Comment by leolara** [comment]
I can confirm that disabling `audit-argument-checks`the problem goes away. Is this a bug here or in `audit-argument-checks` package ?

**Comment by leolara** [comment]
So, this is actually a security flaw in this package, I made a PR
